# DICOM nodes configuration
nodes:
  main:
    host: "localhost"
    port: 4242
    ae_title: "ORTHANC"
    description: "Local Orthanc DICOM server"
  dcm4chee:
    host: "localhost"
    port: 11112
    ae_title: "DCM4CHEE"
    description: "Local dcm4chee DICOM server"
  local_scp:
    host: "127.0.0.1"
    port: 11115
    ae_title: "MCP_SCP"
    description: "Local SCP server for receiving files"

current_node: "dcm4chee"
calling_aet: "MCPSCU"
local_storage_dir: "./dicom_received"
dicomweb_url: "http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs" 